#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.screenlayout/display.sh
nitrogen --restore &

setxkbmap pl &
picom --experimental-backends &
pactl set-source-mute 0 toggle
xsetroot -cursor_name left_ptr

bspc monitor eDP1 -d 1 2 3 4 5 6 7
bspc monitor HDMI1 -d 8

$HOME/.config/polybar/launch.sh

bspc config border_width         3
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#254F79"


bspc rule -a firefox desktop='^1'
bspc rule -a Pavucontrol desktop='^5'
bspc rule -a Spotify desktop='^5'
bspc rule -a Discord desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
